name: Build Distribution

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: The version to use for the package build
      environment:
        type: string
        description: The stage to run (the name of the branch)

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Update Version
      if: ${{ github.event.inputs.environment != main }}
      run: |
        sed -r "s/.*version = (.*).*/version = ${{ github.event.inputs.version }}/" setup.cfg > setup.cfg.tmp
        mv setup.cfg.tmp setup.cfg

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pypa/build
      run: python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
