name: Build and Publish to PyPI

on: push
#  push:
#    branches:
#    - main
#    - development
#  workflow_call:
#    workflows: [
#      "Run Unit Tests"
#    ]

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Update Version
      if: github.ref != 'refs/heads/main'  # testing version
      run: |
        mv setup.cfg setup_t.cfg
        sed -r "s/.*version = (.*).*/version = \1.$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT/" setup_t.cfg > setup.cfg
        rm setup_t.cfg

    - name: Install pypa/build
      run: python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/simpleboto
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/main'  # only publish to PyPI on tag pushes
    needs:
    - build
    - publish-to-testpypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/simpleboto
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
