name: Build and Publish to PyPI

# You can only download artifacts in a workflow that were uploaded during the same workflow run.

on: push
#  push:
#    branches:
#    - main
#    - development
#  workflow_call:
#    workflows: [
#      "Run Unit Tests"
#    ]

env:
  TESTING: ${github.ref != 'refs/heads/main'}  # testing version

jobs:
  get-version:
    uses: ./.github/workflows/update-version.yml
    name: Get Version for PyPI
    with:
      TESTING: env.TESTING

  build:
    name: Build Distribution
    needs:
    - get-version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      if: ${{ env.TESTING == false }}
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pypa/build
      run: python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/simpleboto
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/') && ${{ env.TESTING == false }}  # only publish to PyPI on tag pushes
    needs:
    - build
    - publish-to-testpypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/simpleboto
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
