name: Get PyPI Version

# need master and not in here, so still save version but dont add the github stuff

on:
  workflow_call:

jobs:
  update-version:
    name: Update the Version for the Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Update Version
      run: |
        CURRENT_VERSION=$(grep version setup.cfg | sed -r 's/version = (.*)/\1/')
        NEW_VERSION=$CURRENT_VERSION.$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT
        echo $NEW_VERSION > version.txt
        sed -ir "s/.*version = (.*).*/version = $NEW_VERSION/" setup.cfg

    - name: Store the Version Number
      uses: actions/upload-artifact@v3
      with:
        name: pipeline-package-version
        path: version.txt
